
services:
  postgres:
    container_name: module-03-final
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: module-03-final
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres